chore(renaming): rename libs folder in packages
cloudoperators/juno pull request #109
Opened 2024-07-09 14:29 UTC by andypf

2024-07-09 15:51 UTC, edda approved these changes

2024-07-10 11:25 UTC, ArtieReus requested changes

2024-07-10 11:25 UTC, ArtieReus commented on apps/template/package.json
> +  "name": "@cloudoperators/juno-app-template",
can we also update the package-lock file

2024-07-10 11:25 UTC, ArtieReus commented on packages/template-lib/package.json
> +  "name": "@cloudoperators/juno-template-lib",
please update also package-lock.json

2024-07-10 11:25 UTC, ArtieReus commented on packages/communicator/package.json
> +  "name": "@cloudoperators/juno-communicator",
please update also package-lock.json

2024-07-10 11:42 UTC, ArtieReus approved these changes
lgtm

2024-07-10 11:44 UTC, merged