feat(ui): add FormattedText component
cloudoperators/juno pull request #284
Opened 2024-08-29 14:38 UTC by barsukov

# Summary

Typography and css 

# Changes Made

- FormattedText
- Change 2
- Change 3

# Related Issues

- Issue 1: [link to issue]

# Screenshots (if applicable)

# Testing Instructions

1. `npm i`
2. `npm run TASK`

# Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [ ] My changes generate no new warnings or errors.

2024-09-16 07:49 UTC, barsukov reviewed
Few changes...

2024-09-16 07:49 UTC, barsukov commented on packages/ui-components/src/components/FormattedText/formatted-text.scss
> +// const headCellBaseStyles = `
do we need a comment this ? Maybe just delete it

2024-09-16 07:49 UTC, barsukov commented on packages/ui-components/src/index.js
> +export { FormattedText } from "./components/FormattedText/index.js"
Could you please just remove .js prefix

2024-09-16 14:34 UTC, edda requested changes

2024-09-16 14:34 UTC, edda commented on .changeset/fast-pandas-behave.md
> +"@cloudoperators/juno-ui-components": patch
This adds a new component so should be a minor change instead of patch.
```suggestion
"@cloudoperators/juno-ui-components": minor
```

2024-09-16 14:34 UTC, edda commented on .changeset/gentle-carrots-talk.md
> +---
duplicated changeset. Not sure what happens in this case. I suggest deleting one.

2024-09-18 12:10 UTC, TilmanHaupt approved these changes
lgtm

2024-09-18 14:47 UTC, edda approved these changes

2024-09-18 14:47 UTC, merged