fix(ui): add upload icon into icon lib
cloudoperators/juno pull request #302
Opened 2024-09-04 15:53 UTC by VoigtS

# Summary

During my development duties I noticed that Juno offers a `Download` Icon, but no `Upload` Icon. I would like to include it.

- Add the Icon from the material-design lib
- Bump the juno version

# Screenshots (if applicable)
![image](https://github.com/user-attachments/assets/eab7a54c-d7ba-4851-a1b4-6213f02b7b60)

# Testing Instructions
Open the Storybook, navigate to the Icon section, View the `Upload` Icon

2024-09-05 08:11 UTC, barsukov requested changes
If you would like to introduce new Icon to the Icon.js I would suggest to do the same for IconTs cause we are currently in a migration phase that try to migrate the whole components to TS for that reason please also implement this functionality in IconTS.component.ts

2024-09-05 09:39 UTC, VoigtS commented
> If you would like to introduce new Icon to the Icon.js I would suggest to do the same for IconTs cause we are currently in a migration phase that try to migrate the whole components to TS for that reason please also implement this functionality in IconTS.component.ts

Thank you for the info, I included the icon in the Ts implementation as well.

2024-09-05 12:12 UTC, edda approved these changes

2024-09-06 08:13 UTC, barsukov approved these changes

2024-09-06 08:13 UTC, merged