migration(ui): migrate and adapt supernova from greenhouse extension to juno and fixed exampleapp
cloudoperators/juno pull request #305
Opened 2024-09-05 14:06 UTC by ArtieReus

# Summary

Migrate and adapt supernova from greenhouse extension to juno. Fixed example app by adding missing dependencies.

# Changes Made

- Supernova migration from greenhouse-extension to juno
- Fixed exampleapp by adding missing dependencies

# Related Issues

- Issue 1: [link to issue]

# Screenshots (if applicable)

# Testing Instructions

1. `npm i`
2. `npm run TASK`

# Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [ ] My changes generate no new warnings or errors.

2024-09-05 14:31 UTC, edda requested changes

2024-09-05 14:31 UTC, edda commented on apps/supernova/docker/Dockerfile
> +
`PREDEFINED_FILTERS` is missing here

2024-09-05 14:31 UTC, edda commented on apps/supernova/docker/Dockerfile
> +update_json_field "silenceTemplates" "\$SILENCE_TEMPLATES"
`PREDEFINED_FILTERS` missing

2024-09-05 14:31 UTC, edda commented on apps/supernova/docker/README.md
> +  ```
`PREDEFINED_FILTERS` missing

2024-09-05 14:31 UTC, edda commented on apps/supernova/docker/appProps.sample.json
> +  "silenceTemplates": {}
`predefinedFilters` missing

2024-09-05 14:31 UTC, edda commented on apps/supernova/package.json
> +      "description": "PredefinedFilters are filters applied through TabNavigation in the UI to differentiate between contexts such as Production, QA, and others. They are loaded by default when the a
Need to fix this description
```suggestion
      "description": "PredefinedFilters are groups of filters comprised of a list of filter labels and a regex that is used to filter on the values of that label. They can be thought of as filter categories where the filter logic can be more complex than simple label+values pairs. Predefined filters are defined as an array of objects, where each object is a predefined filter. It contains the display name for the UI as well as a list of filter label + value regex pairs which are AND concatenated when they are being evaluated."
```

2024-09-05 14:43 UTC, ArtieReus commented on apps/supernova/docker/Dockerfile
> +
thx @edda!

2024-09-05 14:44 UTC, ArtieReus commented on apps/supernova/docker/Dockerfile
> +update_json_field "silenceTemplates" "\$SILENCE_TEMPLATES"
thx @edda!

2024-09-05 14:48 UTC, ArtieReus commented on apps/supernova/docker/README.md
> +  ```
thx @edda!

2024-09-06 08:08 UTC, edda requested changes

2024-09-06 08:08 UTC, edda commented on apps/supernova/README.md
> +Specifies filters to be applied in the UI for distinguishing between contexts by matching alerts with regular expressions. These filters are automatically loaded when the application starts. The form
Use same description as in the package.json
```suggestion
PredefinedFilters are filters applied through TabNavigation in the UI to differentiate between contexts such as Production, QA, and others. They are loaded by default when the application is loaded. The format is a list of objects including name, display name and matchers (map containing matchers as name and expression pairs).
```

2024-09-06 08:08 UTC, edda commented on apps/supernova/README.md
> +Defines pre-configured silences available in the schedule silence modal for setting up maintenance windows. The format consists of a list of objects including description, editable_labels (array of s
```suggestion
Defines pre-configured silences available in the schedule silence modal for scheduling future silences. For example when setting up maintenance windows where it is known that certain alerts will fire. The format consists of a list of objects including description, editable_labels (array of strings specifying the labels that users can modify), fixed_labels (map containing fixed labels and their corresponding values), status, and title.
```

2024-09-06 08:10 UTC, edda approved these changes

2024-09-06 08:10 UTC, merged