feat(ui): pageheader custom logo
cloudoperators/juno pull request #363
Opened 2024-09-16 10:37 UTC by barsukov

feat(ui): Pageheader custom logo
This is a duplication of PR https://github.com/cloudoperators/juno/pull/358 that we decided to close during the merge problems.

Allow users to pass a custom logo component to the PageHeader and render it. 

# Changes Made

- use grid layout in header instead of flexbox as it gives us better control to make sure the logo is scaled correctly while keeping its original aspect ratio
- add a `logo` prop that accepts a component to render in a slot
- render the default Juno logo if `true` or `undefined`
- do not render any logo at all if `false` or `null` 

# Related Issues

- #169  
# Screenshots (if applicable)

# Testing Instructions

1. `npm i`
2. `npm run test` / `npm run test PageHeader`

# Checklist

- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings or errors.

2024-09-16 15:36 UTC, edda requested changes

2024-09-16 15:36 UTC, edda commented on packages/ui-components/src/components/PageHeader/PageHeader.component.tsx
>    heading?: string | React.ReactNode | null
The storybook control table displays `any` here instead of the correct types. When you click the "Set object" button this results in a runtime error.

2024-09-16 15:36 UTC, edda commented on packages/ui-components/src/components/PageHeader/PageHeader.component.tsx
> +  logo?: React.ReactNode | (() => React.ReactNode)
This is also displayed as `any` in the storybook table.

2024-09-19 06:59 UTC, edda approved these changes

2024-09-19 09:03 UTC, edda approved these changes

2024-09-19 09:07 UTC, andypf approved these changes

2024-09-19 09:07 UTC, merged