Supernova active silences alerts mapping
cloudoperators/juno pull request #385
Opened 2024-09-17 12:38 UTC by TilmanHaupt

# Summary

Scheduled alerts are now also displayed in the alert details. 
Additionally, the alerts overview now shows only the longest-lasting silence and/or inhibitor.

# Changes Made

- Change 1
- Change 2
- Change 3

# Related Issues

fixes https://github.com/cloudoperators/juno/issues/345
closes https://github.com/cloudoperators/juno/issues/384

# Testing Instructions

1. `npm i`
2. `npm run TASK`

# Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [ ] My changes generate no new warnings or errors.

2024-09-18 08:30 UTC, barsukov commented on apps/supernova/src/components/alerts/AlertStatus.jsx
> +  const inhibitor = useMemo(() => {
Do you really need to wrap this thing and previous one in useMemo?

2024-09-18 08:33 UTC, barsukov requested changes
Let just talk after a call about review

2024-09-18 08:33 UTC, barsukov commented on apps/supernova/src/components/alerts/AlertStatus.jsx
> +    let inhibitedBy = alert.status.inhibitedBy.map((fingerprint) => {
Could you clarify why you mutate same variables here?

2024-09-18 16:19 UTC, barsukov requested changes
Please run prettier on tests, looks like the not right formatting I do not understand why it did not complain on lint

2024-09-18 16:19 UTC, barsukov commented on apps/supernova/src/components/alerts/AlertStatus.test.js
> +  it("Alert to the fingerprint does not exist and should return null", () => {
please use the formate correctly here

2024-09-19 08:34 UTC, barsukov approved these changes
LGTM!

2024-09-19 08:39 UTC, andypf approved these changes

2024-09-19 08:41 UTC, merged