chore(ui): migrate DataGrid components to TypeScript
cloudoperators/juno pull request #389
Opened 2024-09-17 16:48 UTC by gjaskiewicz

# Summary

Migrate DataGrid components to TypeScript

# Changes Made

- Migrate DataGrid components to TypeScript
- Cut out few deps on Button, Stack, Spinner, Search from stories (to be re-introduced)

# Related Issues

- Issue 1: [https://github.com/cloudoperators/juno/issues/224]

# Testing Instructions

1. `npm i`
2. `turbo test`

# Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [ ] My changes generate no new warnings or errors.

2024-09-19 14:42 UTC, barsukov requested changes
Please have a look to few types that could be potentially fixed

2024-09-19 21:12 UTC, gjaskiewicz commented on packages/ui-components/src/components/DataGridFoot/DataGridFoot.component.tsx
> +  children?: React.ReactNode
Done

2024-09-19 21:12 UTC, gjaskiewicz commented on packages/ui-components/src/components/DataGridHeadCell/DataGridHeadCell.component.tsx
> +  children?: React.ReactNode
Done

2024-09-19 21:12 UTC, gjaskiewicz commented on packages/ui-components/src/components/DataGridToolbar/DataGridToolbar.component.tsx
> +  search?: React.ReactNode
Done

2024-09-19 21:12 UTC, gjaskiewicz commented on packages/ui-components/src/components/DataGridToolbar/DataGridToolbar.stories.tsx
> +      control: false,
Done

2024-09-19 21:12 UTC, gjaskiewicz commented on packages/ui-components/src/components/DataGridFoot/DataGridFoot.component.tsx
> +  children?: React.ReactNode
Done

2024-09-20 07:53 UTC, barsukov approved these changes

2024-09-20 08:14 UTC, andypf approved these changes

2024-09-20 08:14 UTC, merged