research(docs): adds a proposal for modulith arch
cloudoperators/juno pull request #449
Opened 2024-09-24 15:01 UTC by andypf

This PR introduces the Modulith Dashboard Architecture (Code Name: Carbon), laying the foundation for a new, scalable, and modular architecture. The architecture is designed to combine the benefits of a monolithic core with modular flexibility, supporting the seamless integration of third-party extensions without compromising performance or stability.

2024-09-24 15:23 UTC, edda requested changes

2024-09-24 15:23 UTC, edda commented on docs/proposals/001_modulith_architecture.md
> +_Example:_
Leftover Example headline.
```suggestion

```

2024-09-24 15:23 UTC, edda commented on docs/proposals/001_modulith_architecture.md
> +> The new Modulith Dashboard must enable seamless updates, interchangeable components, and third-party integrations while maintaining performance and stability.
```suggestion
The new Modulith Dashboard must enable seamless updates, interchangeable components, and third-party integrations while maintaining performance and stability.
```

2024-09-24 15:59 UTC, edda submitted a review, later dismissed

2024-09-25 07:25 UTC, barsukov commented
Please add .mdx as a .prettier ignore to surpass this annoying check.

2024-09-25 07:43 UTC, andypf commented
> Please add .mdx as a .prettier ignore to surpass this annoying check.

it is valid format issue, already fixed

2024-09-25 07:47 UTC, barsukov approved these changes

2024-09-25 11:19 UTC, merged