chore(ui): migrate Button component to TS
cloudoperators/juno pull request #501
Opened 2024-10-08 10:51 UTC by gjaskiewicz

# Summary

Migrate button component to TypeScript

# Changes Made

- migrate Button component to TS
- migrate ButtonRow component to TS

# Related Issues

- Issue 1: [link to issue](https://github.com/cloudoperators/juno/issues/217)

# Testing Instructions

1. `npm i`
2. `turbo test`

# Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [ ] My changes generate no new warnings or errors.

2024-10-08 13:48 UTC, barsukov reviewed
Please fix all comments, I leave them as a comments cause going to leave for few days :)

2024-10-08 13:48 UTC, barsukov commented on packages/ui-components/src/components/Button/Button.test.tsx
> +    screen.getByRole("button").click()
Use here act please

2024-10-08 13:48 UTC, barsukov commented on packages/ui-components/src/components/Button/Button.test.tsx
> +    screen.getByRole("button").click()
Use here act please

2024-10-08 13:48 UTC, barsukov commented on packages/ui-components/src/components/ContentHeading/ContentHeading.stories.tsx
> +// import { Button } from "../../deprecated_js/Button/index.js"
please delete it

2024-10-08 13:48 UTC, barsukov commented on packages/ui-components/src/deprecated_js/Button/button.scss
> +	background-color: var(--color-button-default-bg);
I think again you have a format issue

2024-10-08 22:33 UTC, gjaskiewicz commented on packages/ui-components/src/components/ContentHeading/ContentHeading.stories.tsx
> +// import { Button } from "../../deprecated_js/Button/index.js"
Done

2024-10-08 22:33 UTC, gjaskiewicz commented on packages/ui-components/src/deprecated_js/Button/button.scss
> +	background-color: var(--color-button-default-bg);
Done

2024-10-08 22:33 UTC, gjaskiewicz commented on packages/ui-components/src/components/Button/Button.test.tsx
> +    screen.getByRole("button").click()
Done

2024-10-08 22:34 UTC, gjaskiewicz commented on packages/ui-components/src/components/Button/Button.test.tsx
> +    screen.getByRole("button").click()
Done

2024-10-09 04:31 UTC, andypf requested changes

2024-10-09 04:31 UTC, andypf commented on packages/ui-components/src/components/ContentHeading/ContentHeading.stories.tsx
> +// import { Button } from "../../deprecated_js/Button/index.js"
do we need this commented out code?

2024-10-09 06:12 UTC, gjaskiewicz commented on packages/ui-components/src/components/ContentHeading/ContentHeading.stories.tsx
> +// import { Button } from "../../deprecated_js/Button/index.js"
Done

2024-10-09 11:20 UTC, andypf approved these changes
👍

2024-10-09 11:53 UTC, edda approved these changes

2024-10-09 11:53 UTC, merged