Andypf greenhouse vite2
cloudoperators/juno pull request #527
Opened 2024-10-16 21:55 UTC by andypf

# Summary

This PR migrates Greenhouse Dashboard to Vite, enhancing our build system consistency.

## Additional Notes:
These changes will streamline our build process and improve compatibility within our ecosystem.

# Changes Made

- Removed esbuild-related files.
- Added `vite.config.js` for Vite configuration.
- Introduced the `build:static` script for static builds.
- Updated the `Dockerfile` to replace `build` with `build:static`. This change ensures that Vite generates a build containing an `index.html`, rendering the previous `index.html` in the Docker folder obsolete.
- Modified worker imports in Supernova to use `?worker&inline`. This is crucial for supporting workers within the Greenhouse context. Without `inline`, Vite generates a separate chunk for each worker, which complicates the resolution of hard-coded worker URLs in Supernova. The `inline` option resolves this issue.

# Related Issues

- #429 

# Testing Instructions

1. `npm i`
2. `npm run TASK`

# Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [ ] My changes generate no new warnings or errors.

2024-10-16 21:56 UTC, andypf commented
closes #429

2024-10-18 07:19 UTC, ArtieReus requested changes
checking. Need more time

2024-10-18 07:45 UTC, ArtieReus requested changes

2024-10-18 07:45 UTC, ArtieReus commented on .github/workflows/deploy-pr-preview.yaml
> +          cp -r "$PACKAGE_PATH/$build_folder" "$DEPLOY_PATH/$TARGET_FOLDER"
Once this PR is merged
https://github.com/cloudoperators/juno/pull/472

just do following:
```
  ./.github/scripts/build-vite-app.sh
```

2024-10-18 07:45 UTC, ArtieReus commented on apps/greenhouse/.gitignore
> +appProps.json
Do we need again appProps.json? We have already a global entry for it:
https://github.com/cloudoperators/juno/blob/main/.gitignore#L8

2024-10-18 07:45 UTC, ArtieReus commented on apps/greenhouse/package.json
>      "@testing-library/jest-dom": "^5.17.0",
Do we need this libs?
```
@testing-library/jest-dom
@testing-library/react
```
I removed them from the other vitificatioins.

2024-10-18 07:45 UTC, ArtieReus commented on apps/greenhouse/package.json
>      "assert": "^2.0.0",
This one `"assert": "^2.0.0"` I also removed from the other vitifications.

2024-10-18 07:45 UTC, ArtieReus commented on apps/greenhouse/package.json
>      "postcss-url": "^10.1.3",
This one `postcss-url` also has been removed from the other vitifications.

2024-10-18 07:45 UTC, ArtieReus commented on apps/greenhouse/package.json
> +    "build:static": "node scripts/handle_extensions.js && vite build --mode static",
we still need to add as we did for the other vitifications
```
"serve": "vite preview",
```

2024-10-18 07:45 UTC, ArtieReus commented on apps/greenhouse/package.json
Everything withing the `appProps ` should be migrated to the readme:
https://github.com/cloudoperators/juno/pull/499/files#diff-56db823e2d993fbde8cc3bcca2c0a6fb574ded7b4262e2e685bf8115992d06daR64

2024-10-18 07:45 UTC, ArtieReus commented on apps/greenhouse/package.json
the key `appPreview ` can be removed

2024-10-18 07:45 UTC, ArtieReus commented on apps/greenhouse/vite.config.ts
> +      ...sharedConfig,
we need this for the preview:
```
 base: "./", // Relative Path in Generated index.html
```

2024-10-18 10:29 UTC, closed without merging