chore(ui): migrate ShadowRoot component to TypeScript
cloudoperators/juno pull request #531
Opened 2024-10-17 11:14 UTC by gjaskiewicz

# Summary

Migrate ShadowRoot component to TypeScript

# Changes Made

- migrate ShadowRoot component to TypeScript

# Related Issues

- Issue 1: [[link to issue]](https://github.com/cloudoperators/juno/issues/250)

# Testing Instructions

1. `npm i`
2. `npm run storybook`

# Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [ ] My changes generate no new warnings or errors.

2024-10-17 14:41 UTC, barsukov requested changes
I have one question

2024-10-17 16:32 UTC, gjaskiewicz commented on packages/ui-components/src/components/ShadowRoot/ShadowRoot.component.tsx
> +// TODO: deactivating constructed stylesheets for now because of the decision of the authors to always include constructed stylesheets last
I think it is there: https://github.com/cloudoperators/juno/blob/c3ab4920878a363660b31e5018b04c07420f2f8e/packages/ui-components/src/components/ShadowRoot/ShadowRoot.component.js#L19

I didn't touched comments except of removing typings in comments as those are not in TS

2024-10-18 09:35 UTC, barsukov commented on packages/ui-components/src/components/ShadowRoot/ShadowRoot.component.tsx
> +// TODO: deactivating constructed stylesheets for now because of the decision of the authors to always include constructed stylesheets last
@edda I would like to ask you if we could just leave it like this. Please let us know what do you think.

2024-10-18 14:39 UTC, gjaskiewicz commented on packages/ui-components/src/components/ShadowRoot/ShadowRoot.component.tsx
> +// TODO: deactivating constructed stylesheets for now because of the decision of the authors to always include constructed stylesheets last
@edda Would you be able to take a look?

2024-10-18 14:47 UTC, barsukov approved these changes

2024-10-18 14:47 UTC, andypf approved these changes
lgtm

2024-10-18 14:53 UTC, merged