chore(heureka): improves readme
cloudoperators/juno pull request #546
Opened 2024-10-22 13:39 UTC by hodanoori

# Summary

This PR enhances the Heureka README by adding a general overview of the project and including a link to the backend and API repository. Additionally, screenshots of the currently available views have been incorporated. A "Coming Soon" section has also been added to highlight upcoming features and changes.

# Related Issues

- https://github.com/cloudoperators/juno/issues/433

# Testing Instructions

1. `npm i`
2. `npm run TASK`

# Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [ ] My changes generate no new warnings or errors.

2024-10-22 13:51 UTC, hodanoori commented
- closes https://github.com/cloudoperators/juno/issues/433

2024-10-23 03:07 UTC, andypf submitted a review, later dismissed
lgtm

2024-10-23 08:15 UTC, barsukov requested changes
Looks like screenshots do not work for me

2024-10-23 08:15 UTC, barsukov commented on apps/heureka/README.md
> +![Issue Matches List](../assets/images/heureka_issues_matches_list.png)
<img width="1209" alt="image" src="https://github.com/user-attachments/assets/0737537f-d0cb-480f-af3c-ace69e4c19a3">
Looks like screenshots are not rendered correctly could you double check?

2024-10-23 08:23 UTC, ArtieReus requested changes
checking

2024-10-23 08:31 UTC, ArtieReus requested changes

2024-10-23 08:31 UTC, ArtieReus commented on apps/heureka/README.md
> +  **Coming soon:**
What do you think about creating a separate "Coming Soon" section? The current layout looks a bit off to me. This is a good point to consider in the feature when you want to warn about things.

![Screenshot 2024-10-23 at 10 27 21](https://github.com/user-attachments/assets/051d1a3b-7d9d-44ac-a543-2798343f043c)

2024-10-23 12:43 UTC, barsukov submitted a review, later dismissed
LGTM

2024-10-23 12:56 UTC, ArtieReus requested changes
A very small thing

2024-10-23 12:56 UTC, ArtieReus commented on apps/heureka/README.md
> +This mircro frontend uses the Heureka POC API which aims to:
Sorry... I just have seen this right know... Would be good If we change this since we want to go away of seeing MFA
```suggestion
This standalone UI uses the Heureka POC API which aims to:
```

2024-10-23 12:57 UTC, ArtieReus approved these changes
lgtm

2024-10-23 13:07 UTC, andypf approved these changes
lgtm

2024-10-23 13:08 UTC, merged