chore(docs): adds a decision document for greenhouse/carbon
cloudoperators/juno pull request #548
Opened 2024-10-23 05:59 UTC by andypf

This PR adds a decision document outlining the architecture for the next generation of the Greenhouse Dashboard. The document details key proposals for enhancing extensibility, scalability, and security while integrating extensions effectively.

Key Highlights

	•	Modular Design: Establishes a system for interchangeable modules and extensions.
	•	Routing and Loading: Describes isolated routing for extensions and a unified loading mechanism.
	•	Communication Protocols: Defines secure communication channels between the host and extensions.
	•	Security Measures: Outlines sandboxing, CORS, and authentication strategies.

2024-10-25 08:35 UTC, ArtieReus requested changes

2024-10-25 08:35 UTC, ArtieReus commented on docs/proposals/003_greenhouse.md
Why is this file being removed instead of adapted? I thought this is the target of the proposal. Discuss, agree and change the proposals, not removing them without any agreement

2024-10-25 09:59 UTC, closed without merging

2024-10-25 10:00 UTC, andypf commented
Close this PR because of outdated content.

2024-10-28 11:43 UTC, edda commented on docs/proposals/003_greenhouse.md
I agree with @ArtieReus. We should never delete files once they have been created. If they are superseded by another proposal then add this information to the beginning of the document but don't alter it in any other way.