chore(ui): migrate JsonViewer to typescript
cloudoperators/juno pull request #561
Opened 2024-10-23 17:46 UTC by gjaskiewicz

# Summary

Migrate JsonViewer to typescript

# Changes Made

- migrate JsonViewer to typescript

# Related Issues

- Issue 1: [https://github.com/cloudoperators/juno/issues/232]

# Testing Instructions

1. `npm i`
2. `npm run storybook`

# Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [ ] My changes generate no new warnings or errors.

2024-10-24 04:23 UTC, andypf reviewed
just one small comment from me. 

I can’t say much about TypeScript, but the scope is definitely large, and for that: good job!

2024-10-24 04:23 UTC, andypf commented on packages/ui-components/src/components/JsonViewer/JsonViewer.component.tsx
> +  //extends themes.JsonViewerTheme {
we can remove this line I guess

2024-10-24 08:35 UTC, edda requested changes
The storybook preview is broken. If I read the error message correctly it's because the deprecated version still contains stories:
```
Error: Unable to index files:
- ./src/components/JsonViewer/JsonViewer.stories.tsx,./src/deprecated_js/JsonViewer/JsonViewer.stories.js: Duplicate stories with id: components-jsonviewer--default
- ./src/components/JsonViewer/JsonViewer.stories.tsx,./src/deprecated_js/JsonViewer/JsonViewer.stories.js: Duplicate stories with id: components-jsonviewer--array-data
- ./src/components/JsonViewer/JsonViewer.stories.tsx,./src/deprecated_js/JsonViewer/JsonViewer.stories.js: Duplicate stories with id: components-jsonviewer--light
- ./src/components/JsonViewer/JsonViewer.stories.tsx,./src/deprecated_js/JsonViewer/JsonViewer.stories.js: Duplicate stories with id: components-jsonviewer--expanded
- ./src/components/JsonViewer/JsonViewer.stories.tsx,./src/deprecated_js/JsonViewer/JsonViewer.stories.js: Duplicate stories with id: components-jsonviewer--with-toolbar
- ./src/components/JsonViewer/JsonViewer.stories.tsx,./src/deprecated_js/JsonViewer/JsonViewer.stories.js: Duplicate stories with id: components-jsonviewer--custom-theme
```

2024-10-24 08:56 UTC, barsukov requested changes
My few cents for improving this component

2024-10-24 08:56 UTC, barsukov commented on packages/ui-components/src/components/JsonViewer/JsonViewer.component.tsx
> +interface ThemeColors {
```

type HighlightColors = {
  foreground?: string
  background?: string
}

type ToolbarColors = {
  border?: string
} & HighlightColors

type IconColors = {
  expanded?: string
  collapsed?: string
  expandAll?: string
}

type DataTypeColors = {
  array?: string
  object?: string
  boolean?: string
  date?: string
  float?: string
  function?: string
  integer?: string
  string?: string
  nan?: string
  null?: string
  undefined?: string
  regexp?: string
  background?: string
}

interface ThemeColors {
  background?: string
  ellipsis?: string
  brace?: string
  key?: string
  index?: string
  size?: string
  border?: string
  highlight: HighlightColors
  toolbar: ToolbarColors
  icon: IconColors
  dataType: DataTypeColors
}

```

2024-10-24 08:56 UTC, barsukov commented on packages/ui-components/src/components/JsonViewer/JsonViewer.component.tsx
> +interface ThemeColors {
I would modify it this way to split the big type on chunks and also remove some duplciations that way

2024-10-24 08:56 UTC, barsukov commented on packages/ui-components/src/components/JsonViewer/JsonViewer.component.tsx
> +const ExpandAllIcon = () => {
I would extract this one and other one to nearby components but exported them only to make use inside of this component

2024-10-24 08:56 UTC, barsukov commented on packages/ui-components/src/components/JsonViewer/JsonViewer.component.tsx
> +interface ThemeContextType {
I would extract almost all types to nearby file and called it "JsonViewerTypes.types.ts" but without PropTypes interfaces that should be belong to components.

2024-10-24 08:56 UTC, barsukov commented on packages/ui-components/src/components/JsonViewer/JsonViewer.component.tsx
> +const type = (value: unknown): TypeValueLabelType => {
this method has also potential to refactor with a new typescript way, first way rename it from type to maybe getValueTypeLabel and remove the comment, second:

one of my attemption:
```

function getValueTypeFromObject(value: object | null) {
  if (value === null) return "null"
  if (Array.isArray(value)) return "array"
  if (value instanceof RegExp) return "regexp"
  if (value instanceof Date) return "date"
  return "object"
}

function getValueTypeFromNumber(value: number | null) {
  if (Number.isNaN(value)) return "nan"
  return Number.isInteger(value) ? "integer" : "float"
}

const getTypeOfTheValue = (value: unknown): TypeValueLabelType => {
  switch (typeof value) {
    case "object":
      getValueTypeFromObject(value)
    case "number":
      getValueTypeFromNumber(value as number)
    case "boolean":
      return "boolean"
    case "string":
      return "string"
    case "undefined":
      return "undefined"
    case "function":
      return "function"
    default:
      return "background"
  }
}
```

2024-10-24 13:16 UTC, barsukov requested changes
Very important to not forget to rollback changes and fix other errors

2024-10-24 13:16 UTC, barsukov commented on packages/ui-components/package.json
> +    "storybook": "storybook dev -p 7301 --ci --no-open",
please revert this changes

2024-10-25 07:26 UTC, barsukov requested changes
index.js should be updated too please pay attention to it, do not duplicate parts just remove the .js extensions.

2024-10-25 11:42 UTC, barsukov submitted a review, later dismissed
LGTM!

2024-10-25 11:52 UTC, andypf approved these changes
lgtm

2024-10-25 11:57 UTC, edda requested changes
The storybook documentation for this component looks very ugly because of the superlong strings in the test data. Please remove those edge cases from the test data so that the documentation is better readable.
![Screenshot 2024-10-25 at 13 55 13](https://github.com/user-attachments/assets/fe7de689-3cb0-4b29-ba74-18090d69a28d)

2024-10-25 12:22 UTC, edda approved these changes

2024-10-25 12:24 UTC, barsukov approved these changes

2024-10-25 12:24 UTC, andypf approved these changes
lgtm

2024-10-25 12:25 UTC, merged