feat(docs): add guide for creating an app with Juno UI Components
cloudoperators/juno pull request #679
Opened 2024-12-12 09:02 UTC by ArtieReus

# Summary

This PR introduces documentation on how to create an app using Juno UI Components. The guide covers the setup process, including adding dependencies, configuring Vite, and integrating Juno-specific providers and components into your application.

`This PR does not include any interface descriptions or instructions for integrating the app with Greenhouse or Aurora. Future documentation updates may cover these integrations as needed.`

# Changes Made

- Added a step-by-step guide for creating an app with Juno UI Components.

# Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [ ] My changes generate no new warnings or errors.

2024-12-19 09:14 UTC, ArtieReus commented
@edda do you want to mention anything about the app props `embedded` and `fullWidthContent` for the AppShell?

2024-12-19 09:30 UTC, andypf submitted a review, later dismissed
Great!

2024-12-19 12:56 UTC, andypf commented
@ArtieReus, could you please add a section about bundling? Specifically:
- **Standalone Applications**: For standalone applications, all libraries should be bundled directly into the application.
- **Host-Dependent Applications**: If the application is designed to run on a host that already provides certain libraries, these libraries should not be bundled. Instead, they should be added to the peerDependencies section.

2024-12-19 13:09 UTC, edda approved these changes
I like it a lot! Very good instructions. 
Only thing missing is the info about differences in bundling when building for standalone vs. embedded <- @andypf

2024-12-19 15:04 UTC, barsukov reviewed
LGTM from my side make some changes that was requested and we are good to go

2024-12-20 13:30 UTC, edda commented
> @edda do you want to mention anything about the app props `embedded` and `fullWidthContent` for the AppShell?

Ah yeah, good point. I think it's enough to mention that those props exist and to check the storybook documentation of AppShell for more details (what they do is documented there)

2025-01-03 13:27 UTC, barsukov submitted a review, later dismissed

2025-01-06 15:20 UTC, edda requested changes
Perfect! One small suggestion to make it a bit clearer what people can expect from our host apps.

2025-01-06 15:20 UTC, edda commented on docs/create-your-own-app.md
> +This ensures that the host will provide the necessary libraries, and your application will not attempt to bundle them, avoiding duplication and reducing the size of your application.
```suggestion
This ensures that the host will provide the necessary libraries, and your application will not attempt to bundle them, avoiding duplication and reducing the size of your application. Our host applications will always bundle `@cloudoperators/juno-ui-components`, `react` and `react-dom`, so you should ensure they are added to peer dependencies in your app if it is meant to run within one of those hosts.
```

2025-01-06 17:12 UTC, edda approved these changes

2025-01-08 13:32 UTC, barsukov approved these changes

2025-01-08 13:32 UTC, merged